### ISSUE TITLE
Error when attempting to add lattice to grease pencil object in blender 3.0

### ISSUE THREAD

**Issue by RichMakeGame** [BenjaminSauder/SimpleLattice#6]
thanks for an amazing script by the way, would love to use it with grease pencil objects!

error reads:
Python: Traceback (most recent call last):
  File "C:\Users\rich\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\SimpleLattice-master\op_LatticeCreate.py", line 198, in execute
    self.add_ffd_modifier(objects, lattice, self.group_mapping)
  File "C:\Users\rich\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\SimpleLattice-master\op_LatticeCreate.py", line 337, in add_ffd_modifier
    obj.modifiers[ffd.name].show_in_editmode = True
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1

**Comment by EugeneDudavkin** [comment]
Hello,
sorry for late response.
Made a quick fix. Try it now.
